//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ProductController.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//


package Controllers;


import Models.Platform;
import Models.Product;

public class ProductController {
//	public Models.Product product;

	public static boolean addProduct(Product product) {
		if (Product.exists(product)) {
			System.out.println("Product already exists");
			return false;
		}

		Product.addToDB(product);
		return true;
	}

	public static boolean addSuggestedProduct(Product product) {

		if (Product.existsSuggested(product)) {
			System.out.println("Product already exists");
			return false;
		}

		Product.addToSuggestedDB(product);
		return true;
	}

	public void viewProduct() {

	}

//	public boolean updateProduct(Models.Product product) {
//
//	}
//
//	public boolean deleteProduct() {
//
//	}
//	public boolean applyProduct(Models.Product product) {
//
//	}
//
//	public ArrayList<Product> getProducts(String query) {
//
//	}
}
