//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PromotionController.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Controllers;


public class PromotionController {
	public Models.PromotionCard promo;
	public void viewPromo() {
	
	}
	
	public boolean addGlobalPromo(Models.GlobalPromotion promo) {
	
	}
	
	public boolean addStorPromo(Models.StorePromotion promo) {
	
	}
	
	public boolean deletePromo() {
	
	}
}
