//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ShoppingCartController.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Controllers;


import Models.ShoppingCart;
import Models.StoreProduct;

public class ShoppingCartController {
	public Models.ShoppingCart shoppingCart;

	public ShoppingCartController(ShoppingCart shoppingCart) {
		this.shoppingCart = shoppingCart;
	}

	public boolean addToCart(StoreProduct Product, int Quantity)
	{
		//It Is kinda straight forward here as there is no business logic or validation
		return shoppingCart.addOrder(Product, Quantity);
	}
	//	public boolean creditCheckout() {
//
//	}
//
//	public boolean creditCheckout(Models.PromotionCard promo) {
//
//	}
//
//	public boolean cashCheckout() {
//
//	}
//
//	public boolean cashCheckout(Models.PromotionCard promo) {
//
//	}
//
//	public void viewCart() {
//
//	}
//
//	public boolean addOrder(Models.Product product, Models.Store store) {
//
//	}
}
