//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ShoppingCartController.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Controllers;


public class ShoppingCartController {
	public Models.ShoppingCart shoppingCart;
//	public boolean creditCheckout() {
//
//	}
//
//	public boolean creditCheckout(Models.PromotionCard promo) {
//
//	}
//
//	public boolean cashCheckout() {
//
//	}
//
//	public boolean cashCheckout(Models.PromotionCard promo) {
//
//	}
//
//	public void viewCart() {
//
//	}
//
//	public boolean addOrder(Models.Product product, Models.Store store) {
//
//	}
}
