//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StoreController.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//


package Controllers;


import Models.PhysicalStore;
import Models.Platform;
import Models.StoreOwner;
import Models.VirtualStore;

public class StoreController {
	public Models.Store store;

	public StoreController(String name, String address, StoreOwner storeOwner) {
		store = new PhysicalStore(1 /* temp ID*/, name, address, storeOwner);
		Platform.Stores.add(store);
	}

	public StoreController(String name, StoreOwner storeOwner) {
		store = new VirtualStore(1 /* temp ID*/, name, storeOwner);
		Platform.Stores.add(store);
	}

	public void viewStore() {

	}

//	public boolean applyStore(Models.Store store) {
//
//	}
//
//	public boolean addStore(Models.Store store) {
//
//	}
//
//	public boolean addStoreProduct(Models.Product product, double price) {
//
//	}
//
//	public boolean deleteStoreProduct(Models.Product product) {
//
//	}
}
