//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : UserController.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Controllers;


public class UserController {
	public Models.User user;
	public boolean register(Models.User user) {
	
	}
	
	public void login(String username, String password) {
	
	}
	
	public void setProfilePicture(Image image) {
	
	}
	
	public void updateProfileInfo(Profile profile) {
	
	}
}
