//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : UserController.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Controllers;


import Models.User;

import java.util.HashMap;

public class UserController {
	public Models.User user;
	public boolean register(HashMap<String, String> userData) {
		if (User.exists(userData.get("username"))) return false;

		user = new User(userData);
		User.addUser(user);
		return true;
	}
	
	public boolean login(String username, String password) {
		if (User.exists(username)) {
			User tmp = User.getUser(username);
			if (tmp.passwordHash.equals(password)) {
				user = tmp;
				return true;
			}
		}
		return false;
	}
	
//	public void setProfilePicture(Image image) {
//
//	}
//
//	public void updateProfileInfo(Profile profile) {
//
//	}
}
