//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Address.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Models;


public class Address {
	public String address1;
	public String address2;
	public String country;
	public short zipCode;
//	public boolean verify() {
//
//	}
}
