//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Admin.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Models;


public class Admin extends User {
}
