//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Brand.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Models;


public class Brand {
	public String ID;
	public String name;
}
