//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CCInfo.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Models;


public class CCInfo {
	public String ownerName;
	public String cardNumber;
//	public Date expatriationDate;
	public String securityCode;
//	public boolean verify() {
//
//	}
}
