//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Company.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Models;


public class Company {
	public String ID;
	public String name;
}
