//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GlobalPromotion.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Models;


import java.util.Objects;
import java.util.UUID;

public class GlobalPromotion extends PromotionCard {
    public boolean usePromo(String SerialNumber) {
        for (SerialNumber Serial : SerialNumbers ) {
            if(Objects.equals(Serial.serial, SerialNumber) && !Serial.used) {
                Serial.used = true;
                return true;
            }
        }
        return false;
    }

    public GlobalPromotion(double offPercentage, double offMax) {
        super(offPercentage, offMax);
    }
}
