//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GlobalPromotion.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Models;


import java.util.UUID;

public class GlobalPromotion extends PromotionCard {
    public static boolean addPromo(double offPercentage, double offMax) {
        if(offPercentage > 1) offPercentage = 1;
        if(offPercentage < 0) offPercentage = 0;
        if(offMax < 0) offMax = 0;
        GlobalPromotion newPromo = new GlobalPromotion(offPercentage, offMax);

        //Add 10 Random Serial Numbers
        for (int i = 0; i < 10; i++) {
            newPromo.SerialNumbers.add(new SerialNumber(UUID.randomUUID().toString()));
        }

        //Add To Database
        Platform.PromoCards.add(newPromo);
        return true;
    }

    public GlobalPromotion(double offPercentage, double offMax) {
        super(offPercentage, offMax);
    }
}
