//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GlobalPromotion.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Models;


public class GlobalPromotion extends PromotionCard {

    public GlobalPromotion(double offPercentage, double offMax) {
        super(offPercentage, offMax);
    }
}
