//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Order.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Models;


public class Order {
	public String orderID;
	public StoreProduct product;
	public int quantity;

	public Order(StoreProduct product, int quantity) {
		this.product = product;
		this.quantity = quantity;
	}
}
