//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Order.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Models;


public class Order {
	public String orderID;
	public Product product;
	public Store store;
	public int quantity;
}
