//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PhysiclaProduct.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Models;


public class PhysiclaProduct extends Product {
	public double weight;

	public PhysiclaProduct(String name, String brand, String company, double price, double weight) {
		super(name, brand, company, price);
		this.weight = weight;
	}
}
