//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PhysicalStore.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Models;


public class PhysicalStore extends Store {
	public ArrayList<PhysicalStoreProduct> products;
	public String address;
	public boolean addProduct(Product product, double price) {
	
	}
}
