//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PhysicalProduct.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//


package Models;


import java.util.Scanner;

public class PhysicalProduct extends Product {
	public double weight;

	public PhysicalProduct(String name, String brand, String company, double price, double weight) {
		super(name, brand, company, price);
		this.weight = weight;
	}

	public PhysicalProduct() {
		super();
	}

    @Override
    public void takeInput() {
		super.takeInput();
		Scanner sc = new Scanner(System.in);
		System.out.print("Weight: ");
		price = sc.nextDouble();
	}
}
