//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Platform.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Models;


import java.util.ArrayList;

public class Platform {
	public static ArrayList<User> users = new ArrayList<>();
	public static ArrayList<Product> products = new ArrayList<>();
	public static ArrayList<PromotionCard> promoCards = new ArrayList<>();
}
