//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Platform.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Models;


public class Platform {
	public ArrayList<User> users;
	public ArrayList<Product> products;
	public ArrayList<PromotionCard> promoCards;
}
