//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Product.java
//  @ Date : 14/12/2017
//  @ Author :
//
//

package Models;


public class Product {
	public static int nextID = 0;
	public String ID;
	public String name;
	public String brand;
	public String company;
	public double price;
	//	public DateTime date;
	public boolean accepted;
	public int view = 0;

	public Product() {

	}

	public static boolean addToDB(Product product) {
		product.ID = String.valueOf(nextID++);        //TODO get latest ID from DB if we're saving data.
		Platform.Products.add(product);
		return true;
	}

	public static boolean exists(Product product) {
		return Platform.Products.indexOf(product) != -1;
	}

	public Product(String name, String brand, String company, double price) {
		this.name = name;
		this.brand = brand;
		this.company = company;
		this.price = price;
		this.accepted = false;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null ||
				!Product.class.isAssignableFrom(obj.getClass()))
			return false;

		Product other = (Product) obj;
		return name.equals(other.name) &&
				brand.equals(other.brand) &&
				company.equals(other.company);
	}

	public String viewDetails(){
		view++;
		return "Name: \t" + name + " Brand: \t " + brand +  " Company: \t " + company +  "Avg. Price: \t " + price;
	}

	public static Product getProduct(String name) {
		for (Product product : Platform.Products)
			if (product.name.equals(name))
				return product;
		return null;
	}
}
