//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Product.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Models;


public class Product {
	public String ID;
	public String name;
	public Brand brand;
	public Company company;
	public double price;
//	public DateTime date;
	public boolean accepted;
//	public boolean addProduct() {
//
//	}
//
//	public boolean updateProduct() {
//
//	}
//
//	public boolean deleteProduct() {
//
//	}
}
