//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PromotionCard.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Models;


import java.io.Serializable;
import java.util.ArrayList;
import java.util.Objects;
import java.util.UUID;

public abstract class PromotionCard implements Serializable{
//	public Date expirationDate;
	public double offPercentage;
	public double offMax;
	public ArrayList<SerialNumber> SerialNumbers;
	public boolean verifyPromo(String SerialNumber) {
		for (SerialNumber Serial : SerialNumbers ) {
			if(Objects.equals(Serial.serial, SerialNumber) && !Serial.used)
				return true;
		}
		return false;
	}

	public PromotionCard(double offPercentage, double offMax) {
		this.offPercentage = offPercentage;
		this.offMax = offMax;
	}
}
