//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SerialNumber.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Models;


public class SerialNumber {
	public String serial;
	public boolean used;

	public SerialNumber(String serial) {
		this.serial = serial;
		used = false;
	}
}
