//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ShoppingCart.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Models;


import java.io.Serializable;
import java.util.ArrayList;

public class ShoppingCart implements Serializable {
	public String userID;
	public ArrayList<Order> orders;
	public boolean addOrder(StoreProduct product, int Quantity) {
		orders.add(new Order(product, Quantity));
		return true;
	}

	//TODO Checkout Implementation
}
