//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ShoppingCart.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Models;


public class ShoppingCart {
	public String userID;
//	public ArrayList<Order> orders;
//	public boolean addOrder(Order order) {
//
//	}
}
