//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StoreProduct.java
//  @ Date : 14/12/2017
//  @ Author :
//
//


package Models;


public abstract class StoreProduct {
	public double price;
	public Product product;
	public int view = 0;

	public StoreProduct(Product product, float price) {
		this.product = product;
		this.price = price;
	}
	public  String detailsString(){
		return "Name: " + product.name +  "\t Price: " + price;
	}

	public String viewDetails() {
		product.view++;
		view++;
		return "Name: " + product.name + "\t Brand:  " + product.brand +  "\t Company: " + product.company +  "\t Price: " + price;
	}

	//Console Function
	public void viewAndPrintDetails() {
		System.out.println(viewDetails());
	}

	public int getView() {    //for comparator
		return view;
	}
}
