//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Store.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Models;


import java.io.Serializable;

public abstract class Store implements Serializable{
	public String ID;
	public String name;
	public StoreOwner storeOwner;
	public abstract boolean addProduct(Product product, float Price);

}
