//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Store.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//


package Models;


public abstract class Store {
	public int ID;
	public String name;
	public StoreOwner storeOwner;

	public Store(int ID, String name, StoreOwner storeOwner) {
		this.ID = ID;
		this.name = name;
		this.storeOwner = storeOwner;
	}

	public abstract boolean addProduct(Product product, float Price);
}
