//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StoreOwner.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//


package Models;


import Controllers.StoreController;

import java.util.ArrayList;
import java.util.HashMap;

public class StoreOwner extends User {
	ArrayList<StoreController> stores = new ArrayList<>();

	public boolean hasStore() {
		return stores.isEmpty();
	}

	public StoreOwner(HashMap<String, String> userData) {
		super(userData);
	}

	public boolean addVirtualStore(String name) {
		stores.add(new StoreController(name, this));
		return true; // temporary return
	}

	public boolean addPhysicalStore(String name, String address) {
		stores.add(new StoreController(name, address, this));
		return true; // temporary return
	}
}
