//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Store.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//


package Models;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Scanner;

public abstract class Store implements Serializable{
	public int ID;
	public String name;
	public StoreOwner storeOwner;
	public ArrayList<StoreProduct> products = new ArrayList<>();

	public Store(String name, StoreOwner storeOwner) {
		this.ID = 1; // temp ID
		this.name = name;
		this.storeOwner = storeOwner;
	}

	public static boolean addtoDB(Store store) {
		store.ID = 1;        //TODO get latest ID from DB if we're saving data.
		Platform.Stores.add(store);
		return true;
	}

	public static boolean addtoSuggestedDB(Store store) {
		store.ID = 1;        //TODO get latest ID from DB if we're saving data.
		Platform.SuggestedStores.add(store);
		return true;
	}

	public static boolean exists(Store store) {
		return Platform.Stores.indexOf(store) != -1;
	}

	public abstract boolean addProduct(Product product, float Price);

	@Override
	public boolean equals(Object obj) {
		if (obj == null ||
				!Store.class.isAssignableFrom(obj.getClass()))
			return false;

		Store other = (Store) obj;
		// Stores are compared using their names only
		// So all store names are unique
		return name.equals(other.name);
	}

	public static boolean deleteSuggestedDB(Store store) {
		return Platform.SuggestedStores.remove(store);
	}


	public static Store chooseStores() {
		Scanner sc = new Scanner(System.in);
		int i = 0;
		if (Platform.Stores.size() > 0) {
			for (Store store : Platform.Stores) {
				System.out.println(++i + ". " + store.name);
			}
			System.out.print("Choose Store: ");
			while ((i = sc.nextInt()) < 1 || i > Platform.Stores.size()) //Input-Validation
				System.out.print("Invalid Input");

			return Platform.Stores.get(i - 1);
		} else return null;
	}

	public static Store chooseSuggestedStores() {
		Scanner sc = new Scanner(System.in);
		int i = 0;
		if (Platform.SuggestedStores.size() > 0) {
			for (Store store : Platform.SuggestedStores) {
				System.out.println(++i + ". " + store.name);
			}
			System.out.print("Choose Store: ");
			while ((i = sc.nextInt()) < 1 || i > Platform.SuggestedStores.size()) //Input-Validation
				System.out.print("Invalid Input");

			return Platform.SuggestedStores.get(i - 1);
		} else return null;
	}
}
