//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StoreProduct.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Models;


public class StoreProduct {
	public double price;

	public StoreProduct(float price) {
		this.price = price;
	}
}
