//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StorePromotion.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Models;


public class StorePromotion extends PromotionCard {
	public Store store;
}
