//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StoreOwner.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Models;


public class StoreOwner extends User {
	public Store store;
}
