//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StoreOwner.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//


package Models;


import Controllers.StoreController;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Scanner;

public class StoreOwner extends User {
	private ArrayList<Store> stores = new ArrayList<>();

	public boolean hasStore() {
		return stores.isEmpty();
	}

	public StoreOwner(HashMap<String, String> userData) {
		super(userData);
	}

	public void addStore(Store store) {
		stores.add(store);
	}

	//Console Function
	public Store chooseStores() {
		Scanner sc = new Scanner(System.in);
		int i = 0;
		if(stores.size() > 0) {
			for (Store store : stores) {
				System.out.println(++i + ". " + store.name);
			}
			System.out.print("Choose Store: ");
			while ((i = sc.nextInt()) < 1 || i > stores.size()) //Input-Validation
				System.out.print("Invalid Input");

			return stores.get(i - 1);
		}
		else return null;
	}

	public Store getStore(String name) {
		for (Store store : stores)
			if (store.name.equals(name))
				return store;
		return null;
	}
}
