//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : User.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Models;


public class User {
	public String ID;
	public String name;
	public String username;
	public String birthDate;
	public String passwordHash;
	public Address address;
	public CCInfo CCInfo;
	public ShoppingCart shoppingCart;
	public Image profilePicture;
	public boolean addUser(User user) {
	
	}
	
	public boolean updateUser(User user) {
	
	}
	
	public User getUser(String username, String password) {
	
	}
}
