//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : User.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Models;


import java.util.HashMap;

public class User {
	public static int nextID = 0;
	public int ID;
	public String name;
	public String username;
	public String birthDate;
	public String passwordHash;
	public Address address;
	public CCInfo CCInfo;
	public ShoppingCart shoppingCart;
	//public Image profilePicture;

	public User(HashMap<String, String> userData) {

	}

	public User() {

	}

	/**
	 * @param user user to be added to DB
	 */
	public static void addUser(User user) {
		user.ID = nextID++;
		Platform.users.add(user);
	}

	/**
	 * @param username username to check
	 * @return true if exists
	 */
	public static boolean exists(String username) {
		for (User user : Platform.users)
			if (user.username.equals(username))
				return true;
		return false;
	}
//
//	public boolean updateUser(User user) {
//
//	}
//
	public static User getUser(String username) {
		for (User user : Platform.users)
			if (user.username.equals(username))
				return user;
		return new User();
	}
}
