//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VirtualStore.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Models;


public class VirtualStore extends Store {
//	public ArrayList<VirtualStoreProduct> products;
	public void addProduct(VirtualProduct product, double price) {
	
	}
}
