//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VirtualProduct.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//
package Models;

import java.util.Scanner;

public class VirtualProduct extends Product {
	public String serial;
	public VirtualProduct(String name, String brand, String company, double price, String serial) {
		super(name, brand, company, price);
		this.serial = serial;
	}

	public VirtualProduct() {
		super();
	}

    @Override
    public void takeInput() {
		super.takeInput();
		Scanner sc = new Scanner(System.in);
		System.out.print("Serial: ");	serial = sc.next();		//TODO: Should have a list of Serials(we're using single for prototyping only)
    }
}
