//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VirtualProduct.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Models;


public class VirtualProduct extends Product {
	public String serial;
}
