//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VirtualStoreProduct.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//



package Models;


public class VirtualStoreProduct extends StoreProduct {
    public VirtualStoreProduct(float price, VirtualProduct product) {
        super(price);
        this.product = product;
    }
}
