//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VirtualProduct.java
//  @ Date : 14/12/2017
//  @ Author : 
//
//
package Models;

public class VirtualProduct extends Product {
	public String serial;

	public VirtualProduct(String name, String brand, String company, double price, String serial) {
		super(name, brand, company, price);
		this.serial = serial;
	}
}
